services:
  db:
    image: postgres:16
    container_name: fotliya-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fotliya
      POSTGRES_USER: fotliya
      POSTGRES_PASSWORD: fotliya
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build: api
    container_name: apifly
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  web:
    build: djangoweb
    container_name: djangoweb
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
      - api
    environment:
      DEBUG: "False"
      DB_ENGINE: postgres
      DB_NAME: fotliya
      DB_USER: fotliya
      DB_PASSWORD: fotliya
      DB_HOST: db
      DB_PORT: "5432"
      API_URL: http://api:8000
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: