# Generated by Django 6.0.2 on 2026-05-13 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotLiYa', '0002_question_remove_gamesession_finished_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(blank=True, default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('proposed', 'Proposada')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ProposedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('mechanics', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendent'), ('approved', 'Aprovada'), ('rejected', 'Rebutjada')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
