# Generated by Django 6.0.2 on 2026-05-13 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotLiYa', '0003_gamesession_game_type_gamesession_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-started_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='proposedquestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='gamesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposedquestion',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proposedquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='proposedquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendent'), ('approved', 'Aprovada'), ('rejected', 'Rebutjada')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('proposed', 'Proposada')], db_index=True, default='proposed', max_length=20),
        ),
    ]
