# Generated by Django 6.0.2 on 2026-05-14 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotLiYa', '0003_gamesession_game_type_question_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedquestion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
