# Generated by Django 6.0.2 on 2026-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotLiYa', '0004_alter_answer_options_alter_gamesession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('proposed', 'Proposada')], db_index=True, default='manual', max_length=20),
        ),
    ]
